# Generated by Django 5.0rc1 on 2023-11-24 05:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.productcategory'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image_1',
            field=models.ImageField(upload_to='uploads/images'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image_2',
            field=models.ImageField(upload_to='uploads/images'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image_3',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/images'),
        ),
    ]
